### PR TITLE
Require a certain amount of talking to return audio

### PR DESCRIPTION
**Pull request by MatthewScholefield**
Otherwise, a little sound will trigger listening and Khronos will respond with something like "I couldn't understand that".

### CODE REVIEW

**Comment by syb0rg** [comment]
@MatthewScholefield Is this number arbitrarily picked?  Or was it based on some metric such as average time it takes to say a small word?

**Comment by MatthewScholefield** [comment]
I tried saying Hello and measured how long it took. It normally took around 9-10 buffers.

**Comment by syb0rg** [comment]
Looks good to me, and is a good way to handle this given the current speech recognition system.

The next implementation of speech recognition (described [here](https://github.com/syb0rg/Khronos/projects/2)) should look at the "meaning" behind the sound and disregard it if it is noise.

**Comment by MatthewScholefield** [comment]
Yeah, just really a quick fix I had to do to even get it to work.
Otherwise, it just sits there, infinitely listening.

**Pull request merged**
