### PR TITLE
Add dynamic talking threshold to support more hardware

### PR DESCRIPTION
**Pull request by MatthewScholefield**
On my laptop, the talking threshold is wayy too low. So, I made it adjust over time to accommodate for different microphones.

### CODE REVIEW

**Comment by syb0rg** [comment]
@MatthewScholefield  Could you walk me through what you're trying to do here?  Is this code implementing moving averages?  Comments would help out a lot (somewhat ironic me asking you to do that since I don't have many myself... I'm working on it haha).  Also, could you fix the indentation?  My indentations are 4 spaces, while yours seem to be 2 spaces.

**Comment by MatthewScholefield** [comment]
I'll add some comments. The code updates the threshold, keeping it above the average when silent or below the average when talking, by the trigger ratio. For instance, if when silent, the average rms is 1.0, it will take an rms of 4.0 to activate it (`if (talkingIntensity > talkingThreshold)`), but then it will divide by the trigger ratio and require the volume to lower back to 1.0 to be counted as silent.

**Comment by syb0rg** [comment]
@MatthewScholefield It looks like you tried to fix the indentation... but if you look at the "files changed" link you can see there's still something off about it.

**Comment by MatthewScholefield** [comment]
Oh, no I haven't gotten to fixing the indentation yet. I probably just used
tabs rather than spaces.

**Comment by MatthewScholefield** [comment]
@syb0rg I've fixed the indentation and merge conflicts.

**Comment by syb0rg** [comment]
@MatthewScholefield Awesome work, thanks!

**Pull request merged**
